### ISSUE TITLE
[Bug] Fix service messages with self class

### ISSUE THREAD

**Issue by nielsvanvelzen** [HetIsNiels/hangout#18]
![image](https://cloud.githubusercontent.com/assets/2305178/19185187/d6089af0-8c80-11e6-932c-28eae454a478.png)

Should probably add the following CSS:

``` css
.message.self.service {
    margin: 0;
}
```
